spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

---
spring:
  config.activate.on-profile: test
  datasource:
    hikari.jdbc-url: jdbc:h2:mem:test_db;MODE=MySQL;
    username: sa
    password:

---
spring:
  config.activate.on-profile: local

