spring:
  application:
    name: event-supporter

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml

  profiles:
    active: local
